### ISSUE TITLE
Be Cool, Be Fancy

### ISSUE THREAD

**Issue by CAnorbo** [molnard/The-release-game-v2-0-4-1#1]
**:scroll: Preamble:**

Be Cool, Be Fancy

**:book: TL;DR - Too Long, Didn’t Read:**

Make the design of the wallet more simple and cool.

**:star2: Specification, Scope, and Features:**

- Get rid of the blue color
- Make the UI more simple
- Rethinked design elements, and fonts that are easier to read.
- Add the btc/sats/dollars amount switcher.

**:crossed_swords: Motivation:**

I feel our software is really clear but the design is not fit for 2023.
Roland made a great concept for a Mobile wallet that has an epic design, we should use that style for our desktop wallet.

**:scroll: Rationale:**

The inspiration was Roland’s mobile wallet concept.

**:milky_way: Backward Compatibility:**

I can’t see any issue.

**:books: Reference Implementation (optional):**

Attached an image about the concept.

![](https://imgtr.ee/images/2023/09/14/e38c3e7d962bbe44f65beb1051e51752.jpeg)

**Comment by molnard** [comment]
Very nice, please add more text and format it like https://github.com/molnard/The-release-game-v2-0-4-1/issues/4

**Comment by molnard** [comment]
Remember you need to "sell" the idea.

**Comment by molnard** [comment]
Other Quests are about the same goal but in a more detailed way. The author agreed to close this in prior to them.
