### ISSUE TITLE
Restore the power of the Binoculars of Privacy Progress

### ISSUE THREAD

**Issue by BTCparadigm** [molnard/The-release-game-v2-0-4-1#11]
**📜 Preamble**

Restore the power of the Binoculars of Privacy Progress.

**📖 TL;DR - Too Long, Didn't Read**

The vision enchantment of the Binoculars of Privacy Progress has worn off and should be restored. 
You must convince the high elfs of Revertium to recast the original spell, which allowes the wearer to get insights about their own kingdom and the fellow troops. 

**🌟 Specification, Scope, and Features**

1. Make the Privacy Progress Bar color differences clear again, although not as bright as the original ones. 
2. Put back the coin segments. 
3. Show the bar even when Progress is 0.

**⚔️ Motivation**

The Binoculars got conceptually worse after they were found, except for the color brightness. They are now less intuitive and more confusing for both newbies and advanced users, based on my own experience and the feedback I got from other users.

**📜 Rationale**

1. Red, yellow and green are much more intuitive colors for Privacy Progress and UTXO status, than shades of green. We need to be able to clearly distinguinsh our kingdom's colors from our foes.
2. We need to see our troops clearly in order to manage them properly. Not everyone uses the defaults all the time and this is a great example case about how to please and help advanced missionaries, without bothering newbies. If it looks ugly because of too many small coins, the problem is probably not in the Privacy Progress Bar but somewhere else. 
3. Having such a small visual feedback is useful and covenient for those who understand it, and easily ignorable or educating for those who dont understand it right away.

**🌌 Backward Compatibility**

Not a problem

**📚 Reference Implementation (optional)**

1. https://github.com/zkSNACKs/WalletWasabi/issues/8180 and the PR/issue where the colors got changed.
2. https://github.com/zkSNACKs/WalletWasabi/issues/11355.
3. https://github.com/zkSNACKs/WalletWasabi/issues/11425.

**Comment by molnard** [comment]
@soosr vetoed - discussed on the meeting, quick and inaccurate notes from me: 

- Segments removed to reduce the cognitive load, in consensus in the UI team - should not add it back. 
- Should not be in the default workflow.
- Hard to notice the difference in the number of coins if there are a lot. 
- Maintenance burden - took a lot of time no clear effort.
