### ISSUE TITLE
Make it easy on the eyes and light on the fingertips

### ISSUE THREAD

**Issue by ghost** [molnard/The-release-game-v2-0-4-1#16]
**📜 Preamble**

Many people would like to, but cannot use Wasabi because they cannot see or touch it.

**📖 TL;DR - Too Long, Didn't Read**

Make Wasabi accessible to all.

**🌟 Specification, Scope, and Features**

- keyboard navigation
- screen reader support
- high-contrast themes.

**⚔️ Motivation**

Anonymity loves company. 

Visual disability: 2 billion
Physical disability: 1.5 billion

**🌌 Backward Compatibility**

There is some existing keyboard navigation.

**Comment by molnard** [comment]
- Too many resources for too limited reach (in the Bitcoin ecosystem).
