### ISSUE TITLE
Lipstick on a pig

### ISSUE THREAD

**Issue by ghost** [molnard/The-release-game-v2-0-4-1#17]
**📜 Preamble**

Create more themes. 

**📖 TL;DR - Too Long, Didn't Read**

Some like it black, some white, others love grey, or blue, and even pink, let a thousand flowers bloom and give people the UI theme they love best.

**🌟 Specification, Scope, and Features**

We can have themes of many colors:
- lights out
- dark
- light
- white
- high contrast
- blue
- green
- pink
- purple

**⚔️ Motivation**

Because who doesn't love a good color scheme? With so many colors to choose from, you can finally match your software to your mood. It distracts users from fact that Wasabi is heavy software: "oh look, it's pink, it can't be so hard to use!" 

**📜 Rationale**

The extra custpmizability is a delight to users, it's an accessibility improvement, and arguably even a slight privacy improvement, as a shoulder surfer might not recognize Wasabi in a pink theme.

**🌌 Backward Compatibility**

We can take this opportunity to freshen up the two existing themes.

**Comment by molnard** [comment]
- Vetoed by @nopara73 reason: "normal veto".
