### ISSUE TITLE
Document the code

### ISSUE THREAD

**Issue by turbolay** [molnard/The-release-game-v2-0-4-1#19]
**📖 TL;DR - Too Long, Didn't Read**

Too many pieces of the software are too hard to understand, it would help a lot to provide useful technical documentation for them.

**🌟 Specification, Scope, and Features**

Write better comments, or write documents referenced in the code itself to explain how components work.
Non exhaustive list of components that would benefit from this: `CoinsRegistry`, `TransactionProcessor`, `AmountDecomposer`, `BlockchainAnalyzer`, `SmartCoinSelector`, `CoinsSelectorForCoinjoin`...

**⚔️ Motivation**

I had to gain context on many different components, and every time it's the same pain. Comments are almost never useful, old PRs have almost no explanation at all either.

**📜 Rationale**

N/A

**🌌 Backward Compatibility**

N/A

**📚 Reference Implementation (optional)**

2 examples where I tried to explain what my code is doing:
- https://github.com/zkSNACKs/WalletWasabi/discussions/11222
- [GetDestinationAddresses()](https://github.com/zkSNACKs/WalletWasabi/blob/b0fe82740748e4d46da825b100209998e99c5afe/WalletWasabi/Blockchain/Transactions/SmartTransactionExtensions.cs#L41)

**Comment by molnard** [comment]
- Not aligned with the prophecy. @molnard
- Good code should explain itself. Should change the code instead. @kristapsk
- This is happening all the time without aiming it. @lontivero
