### ISSUE TITLE
Simplify the code

### ISSUE THREAD

**Issue by turbolay** [molnard/The-release-game-v2-0-4-1#20]
**📖 TL;DR - Too Long, Didn't Read**

Make the code simpler by refactoring.

**🌟 Specification, Scope, and Features**

Many controls or backend components are just a melting pot of features that are too hard to understand, I can't have a direct list because one really has to have context on a component to understand that. The `CoinsRegistry` is a great example that would need some love. Same as the `TransactionSummary` that is basically adding complexity for the sake of adding complexity.

**⚔️ Motivation**

Too many pieces of the software are being increasingly complex over time for the only reason that we are adding layers and layers each time we find a problem. We could refactor many classes to make them much more easier and don't rely on many different objects. In some cases renaming variables could also help.

**📜 Rationale**

N/A

**🌌 Backward Compatibility**

N/A

**📚 Reference Implementation (optional)**

- #11516
- #11458
- #11506
- UI Decoupling

**Comment by molnard** [comment]
- This is something that we do anyway. @lontivero
- Too general. I need concrete ideas on what, why, and how to refactor and what is the benefit. @molnard
