### ISSUE TITLE
Explain what we are doing

### ISSUE THREAD

**Issue by turbolay** [molnard/The-release-game-v2-0-4-1#21]
**📖 TL;DR - Too Long, Didn't Read**

Wasabi is a black box, and we need to explain it better to users, even trade-offs.

**🌟 Specification, Scope, and Features**

Using tooltips, ⓘ button, links to the doc....
For topics such as blacklisting, that we can't CPFP optimally, perks of automatic coin selection for payment and coinjoins, why my coinjoin is not confirming, some of the music box message, password/passphrase...

**⚔️ Motivation**

Nobody likes to use something that they don't understand, and nobody understands Wasabi. It suffers 2 problems:
- The concepts of the software are complex on their own
- The choice of sleek and "empty" UI makes us to always prefer to avoid provinding explanations.

Many users could think we are doing stupid things, irrational. Yet, we almost always have a rationale for what we are doing, even the trade-offs. Explaining them would be much much better.

**📜 Rationale**

N/A

**🌌 Backward Compatibility**

N/A

**📚 Reference Implementation (optional)**

- https://github.com/zkSNACKs/WalletWasabi/pull/11102 is a really great example IMO of this being done properly.

**Comment by molnard** [comment]
Noble Author,

Your Quest has been selected for further progress! The devil is in the details - so you need to elaborate and show your quest is not evil. We only embrace quests that are leading us to the light! To prove that you will need to add the following Sections to the Quest description above: 

**⚠️ Sections to add to the Quest descriptions**

- Team involvement: [ui / code / integrations / marketing ] can be one or more. 
- Subtasks. Try to break it down as much as possible. Think about teams and jobs that can be done in parallel. Phrase it like a Todo list with elements. If something is not clear yet do not forget to add a task - "research this or that"... 

**ℹ️ Tips** 

- Try to break down the task to Teams and then to Subtasks. 
- Try to be as detailed as possible. 
- Do your best to estimate or to get an estimation from the right ppl. 
If required you can arrange a meeting and invite team leaders or ppl you believe could be involved or have something to add. 

🕐  Please make this the utmost importance - we do not have much time left!
