### ISSUE TITLE
Chatbot for the doc

### ISSUE THREAD

**Issue by turbolay** [molnard/The-release-game-v2-0-4-1#23]
**📖 TL;DR - Too Long, Didn't Read**

Have a chatbot trained with the documentation and github discussions to assist users.

**🌟 Specification, Scope, and Features**

The best implementation would be in the software, as users can make use of the bundled tor instance to access it

**⚔️ Motivation**

The doc is extremely good and complete, but navigating into it is sometimes too hard. I'm sure it would help many users getting familiarized with the software and answering questions themselves. Also asking for support is annoying for them as they need an account.

**📜 Rationale**

Users might reveal some information in the chat. It might leak IP to third party but it would be ok with tor. Sometimes the bot might also goes wild. Also it will cost us a bit of money.

**🌌 Backward Compatibility**

N/A

**Comment by molnard** [comment]
Vetoed - Out of scope by the Prophecy @bharmat
