### ISSUE TITLE
Competition for RoninDojo

### ISSUE THREAD

**Issue by turbolay** [molnard/The-release-game-v2-0-4-1#24]
**📖 TL;DR - Too Long, Didn't Read**

Wasabi currently doesn't offer competition to RoninDojo

**🌟 Specification, Scope, and Features**

I believe the most clever way would be an integration on Start9

**⚔️ Motivation**

Users with such complete full node integration must have more Bitcoin on average that standard users, and it's a slice of users that we are straight losing.

**📜 Rationale**

We need a privacy focused OS, but that exposes Tor port controls. It might be easier with Arti.

**🌌 Backward Compatibility**

N/A

**Comment by molnard** [comment]
- Not aligned with the prophecy. @lontivero
- Out of scope. @bharmat
