### ISSUE TITLE
The price of freedom

### ISSUE THREAD

**Issue by hgergoil** [molnard/The-release-game-v2-0-4-1#8]
**📜 Preamble**

> CJ fee increase by @hgergoil 

**🌟 Specification, Scope, and Features**

> CJ fee increase to 0,05%.

**⚔️ Motivation**

> Give more bonus for everyone.

**📜 Rationale**

> Unfortunately, the current fee structure did not live up to expectations. I think those who value privacy are willing to pay more, and even so, freedom is cheap.

**Comment by molnard** [comment]
Voted by @nopara73 reason: "over my dead body".
