### ISSUE TITLE
Speak my language, stupid robot! 

### ISSUE THREAD

**Issue by ghost** [molnard/The-release-game-v2-0-4-1#9]
**📖 TL;DR - Too Long, Didn't Read**

Many people don't understand English, but still desire privacy. 

**🌟 Specification, Scope, and Features**

Translate the wallet UI to the most spoken languages, display the UI in the users language automagically, consider other nuances like left-to-right languages, time and currency notations in the design.

**⚔️ Motivation**

Anonymity loves company. 

English - 1.4+ billion
Mandarin Chinese - 1.1+ billion 
Hindi - 602+ million
Spanish - 548+ million 
Arabic - 422+ million 
Bengali - 300+ million 

**📜 Rationale**

Reach a larger audience and increase user satisfaction

**Comment by molnard** [comment]
- This is a separate project in itself. Translations, development, and many other aspects that we would need to deal with while we have other large enough projects to manage. @bharmat
